[package]
name = "adept2-sys"
description = "Bindings to Digilent Adept2 APIs"
authors = ["Dan Glastonbury <dglastonbury@mozilla.com>"]
version = "0.1.0"
license = "MIT/Apache-2.0"
repository = "https://github.com/djg/adept2-rs"

build = "build.rs"

[dependencies]
